name: ci

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dev dependencies
        run: pip install -r dev-requirements.txt
      - name: Run linter
        run: ruff check

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Run unit tests
        run: python -m unittest
      - name: Build micropython
        run: |
          git clone --depth 1 https://github.com/micropython/micropython.git
          cd micropython
          git submodule update --init
          make -C mpy-cross
          cp mpy-cross/build/mpy-cross /usr/local/bin/
          make -C ports/unix
          cp ports/unix/build-standard/micropython /usr/local/bin/
          cd ..
          rm -rf micropython
      - name: Install e2e test dependencies
        run: ./bin/setup
      - name: Install mosquitto
        run: |
          sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
          sudo apt-get update
          sudo apt-get install -y mosquitto
      - name: Generate test certificate for MQTTS
        run: ./bin/generate_cert
      - name: Set password for shell
        run: |
          mosquitto_passwd -c -b mosquitto_passwords test_user test_pass
          chmod 700 mosquitto_passwords
      - name: Run integration tests
        run: ./bin/test_e2e
